-- 코드를 작성해주세요
SELECT (CASE WHEN 01 <= MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE) <= 03 THEN '1Q'
WHEN 04 <= MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE) <= 06 THEN '2Q'
WHEN 07 <= MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE) <= 09 THEN '3Q'
WHEN 10 <= MONTH(DIFFERENTIATION_DATE) AND MONTH(DIFFERENTIATION_DATE) <=  12 THEN '4Q' 
        END) as QUARTER,
COUNT(*) as ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER