-- 코드를 작성해주세요
SELECT b.ITEM_ID, c.ITEM_NAME, c.RARITY 
FROM ITEM_INFO a
INNER JOIN ITEM_TREE b
ON a.ITEM_ID = b.PARENT_ITEM_ID
INNER JOIN ITEM_INFO c
ON b.ITEM_ID = c.ITEM_ID
WHERE a.RARITY = 'RARE'
ORDER BY b.ITEM_ID DESC