-- 코드를 작성해주세요
SELECT f.ID, n.FISH_NAME, f.LENGTH 
FROM (SELECT *, MAX(LENGTH) OVER (PARTITION BY FISH_TYPE) as MAX_LENGTH FROM FISH_INFO) f
INNER JOIN FISH_NAME_INFO n ON f.FISH_TYPE = n.FISH_TYPE
WHERE f.LENGTH = f.MAX_LENGTH
ORDER BY f.ID