-- 코드를 작성해주세요
SELECT SUM(SCORE) as SCORE, a.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL
FROM HR_EMPLOYEES a 
INNER JOIN HR_GRADE b
ON a.EMP_NO = b.EMP_NO
GROUP BY b.EMP_NO, b.YEAR
ORDER BY SCORE DESC
LIMIT 1