-- 코드를 작성해주세요
SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (SELECT SUM(b.SCORE) as SCORE, a.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL,
     RANK() OVER(ORDER BY SUM(b.SCORE) DESC) as rk
     FROM HR_EMPLOYEES a
     INNER JOIN HR_GRADE b
     ON a.EMP_NO = b.EMP_NO
      WHERE b.YEAR = 2022
     GROUP BY a.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL) as c
WHERE c.rk = 1