-- 코드를 입력하세요
SELECT a.CATEGORY, SUM(b.SALES) as TOTAL_SALES
FROM BOOK a
INNER JOIN BOOK_SALES b
ON a.BOOK_ID = b.BOOK_ID
WHERE DATE_FORMAT(b.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY